name: Manual Go Build & Docker Push

on:
  workflow_dispatch:

env:
  IMAGE_REGISTRY: registry.cn-hangzhou.aliyuncs.com
  IMAGE_NAME: skyline

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: Build Go binary
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o skyline . -ldflags="-extldflags '-static'"

      - name: Log in to Aliyun Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          DATE_TAG=$(date +%Y%m%d)
          IMAGE=${{ env.IMAGE_REGISTRY }}/${{ secrets.IMAGE_NAMESPACE }}/${{ env.IMAGE_NAME }}:$DATE_TAG
          echo "Building Docker image: $IMAGE"
          docker build -t $IMAGE .
          docker push $IMAGE
